---
blank_issues_enabled: false
contact_links:
  - name: I have a question or need support
    url: https://ai-speaker.discourse.group/
    about: Check the community forum for help.
  - name: Feature Request
    url: https://github.com/sviete/ais-ha-addon-cloudflared/discussions/new
    about: Please use create a Discussions for making feature requests.
  - name: Cloudflared related issues
    url: https://github.com/cloudflare/cloudflared
    about: Issues related to the tunnel itself should be addressed here.
