---
name: AIS Cloudflared
version: dev
slug: cloudflared
description: "Use Cloudflare's AIS Tunnel to remotely connect to Home Assistant without opening any ports"
url: "https://github.com/sviete/ais-ha-addon-cloudflared/"
codenotary: info@ai-speaker.com
init: false
hassio_api: true
hassio_role: homeassistant
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl:rw
  - share:rw
  - config:rw
options:
  ais_subdomain: ""
  ais_password: ""
  log_level: "info"
schema:
  ais_subdomain: str
  ais_password: password
  log_level: list(trace|debug|info|notice|warning|error|fatal)
